-- ============================================================
-- Gestión de Flota — Oracle DDL
-- Script 01: Creación de tablas, relaciones y constraints
-- ============================================================

-- ─── EMPRESAS ───────────────────────────────────────────────
CREATE TABLE EMPRESAS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    RUT             VARCHAR2(20)    NOT NULL UNIQUE,
    GIRO            VARCHAR2(200),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100),
    TELEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    PLAN            VARCHAR2(20)    DEFAULT 'STANDARD' NOT NULL,
    ACTIVA          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_EMPRESA_PLAN CHECK (PLAN IN ('STARTER','STANDARD','PREMIUM')),
    CONSTRAINT CHK_EMPRESA_ACTIVA CHECK (ACTIVA IN (0,1))
);

-- ─── USUARIOS DEL SISTEMA ───────────────────────────────────
CREATE TABLE USUARIOS_SISTEMA (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    AZURE_OID       VARCHAR2(36)    UNIQUE,          -- Object ID de Azure B2C
    NOMBRE          VARCHAR2(200)   NOT NULL,
    EMAIL           VARCHAR2(150)   NOT NULL,
    ROL             VARCHAR2(30)    NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_USR_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT CHK_USR_ROL CHECK (ROL IN ('ADMIN','SUPERVISOR','JEFE_TALLER','OPERADOR','CONDUCTOR','BODEGA')),
    CONSTRAINT CHK_USR_ACTIVO CHECK (ACTIVO IN (0,1)),
    CONSTRAINT UQ_USR_EMAIL_EMP UNIQUE (EMPRESA_ID, EMAIL)
);

-- ─── CLIENTES ───────────────────────────────────────────────
CREATE TABLE CLIENTES (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    RUT             VARCHAR2(20)    NOT NULL,
    RAZON_SOCIAL    VARCHAR2(200)   NOT NULL,
    GIRO            VARCHAR2(200),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100),
    PAIS            VARCHAR2(100)   DEFAULT 'Chile',
    TELEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    REP_LEGAL_NOMBRE VARCHAR2(200),
    REP_LEGAL_RUT   VARCHAR2(20),
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CLI_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT UQ_CLI_RUT_EMP UNIQUE (EMPRESA_ID, RUT),
    CONSTRAINT CHK_CLI_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- ─── VEHÍCULOS ──────────────────────────────────────────────
CREATE TABLE VEHICULOS (
    ID                      VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID              VARCHAR2(36)    NOT NULL,
    PATENTE                 VARCHAR2(10)    NOT NULL,
    MARCA                   VARCHAR2(100)   NOT NULL,
    MODELO                  VARCHAR2(100)   NOT NULL,
    ANIO                    NUMBER(4)       NOT NULL,
    TIPO                    VARCHAR2(30)    NOT NULL,
    COMBUSTIBLE             VARCHAR2(20)    DEFAULT 'DIESEL' NOT NULL,
    ESTADO                  VARCHAR2(30)    DEFAULT 'OPERATIVO' NOT NULL,
    KM_ACTUALES             NUMBER(12)      DEFAULT 0 NOT NULL,
    KM_PROXIMO_SERVICIO     NUMBER(12)      DEFAULT 0 NOT NULL,
    VENCIMIENTO_REVISION    DATE,
    VENCIMIENTO_PERMISO     DATE,
    COLOR                   VARCHAR2(50),
    NUM_MOTOR               VARCHAR2(50),
    NUM_CHASIS              VARCHAR2(50),
    QR_CODE                 VARCHAR2(100)   UNIQUE,   -- código QR del camión
    CAPACIDAD_ESTANQUE      NUMBER(6),                -- litros de combustible
    TARA_KG                 NUMBER(8),                -- peso tara en kg
    CAPACIDAD_CARGA_KG      NUMBER(8),                -- capacidad de carga en kg
    ELIMINADO               NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_VEH_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT UQ_VEH_PATENTE_EMP UNIQUE (EMPRESA_ID, PATENTE),
    CONSTRAINT CHK_VEH_TIPO CHECK (TIPO IN ('CAMION','BUS','FURGON','CAMIONETA','OTRO')),
    CONSTRAINT CHK_VEH_COMBUSTIBLE CHECK (COMBUSTIBLE IN ('DIESEL','GASOLINA','GAS','ELECTRICO')),
    CONSTRAINT CHK_VEH_ESTADO CHECK (ESTADO IN ('OPERATIVO','EN_TALLER','FUERA_SERVICIO')),
    CONSTRAINT CHK_VEH_ELIMINADO CHECK (ELIMINADO IN (0,1))
);

-- ─── CONDUCTORES ────────────────────────────────────────────
CREATE TABLE CONDUCTORES (
    ID                      VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID              VARCHAR2(36)    NOT NULL,
    USUARIO_ID              VARCHAR2(36),               -- vínculo con USUARIOS_SISTEMA
    NOMBRE                  VARCHAR2(200)   NOT NULL,
    RUT                     VARCHAR2(20)    NOT NULL,
    TELEFONO                VARCHAR2(20),
    EMAIL                   VARCHAR2(150),
    CATEGORIA_LICENCIA      VARCHAR2(5)     NOT NULL,
    VENCIMIENTO_LICENCIA    DATE            NOT NULL,
    ESTADO                  VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    SCORE_CONDUCCION        NUMBER(3)       DEFAULT 100,
    HORAS_MES               NUMBER(6,1)     DEFAULT 0,
    KM_MES                  NUMBER(10)      DEFAULT 0,
    INFRACCIONES_MES        NUMBER(5)       DEFAULT 0,
    ELIMINADO               NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COND_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_COND_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS_SISTEMA(ID),
    CONSTRAINT UQ_COND_RUT_EMP UNIQUE (EMPRESA_ID, RUT),
    CONSTRAINT CHK_COND_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','VACACIONES')),
    CONSTRAINT CHK_COND_SCORE CHECK (SCORE_CONDUCCION BETWEEN 0 AND 100),
    CONSTRAINT CHK_COND_ELIMINADO CHECK (ELIMINADO IN (0,1))
);

-- ─── ASIGNACIONES ───────────────────────────────────────────
CREATE TABLE ASIGNACIONES (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    VEHICULO_ID     VARCHAR2(36)    NOT NULL,
    CONDUCTOR_ID    VARCHAR2(36)    NOT NULL,
    FECHA_INICIO    DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_FIN       DATE,
    ACTIVA          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ASIG_EMPRESA   FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_ASIG_VEHICULO  FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_ASIG_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES(ID),
    CONSTRAINT CHK_ASIG_ACTIVA CHECK (ACTIVA IN (0,1))
);

-- ─── GPS TRACKS ─────────────────────────────────────────────
CREATE TABLE GPS_TRACKS (
    ID              NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    VEHICULO_ID     VARCHAR2(36)    NOT NULL,
    CONDUCTOR_ID    VARCHAR2(36),
    LATITUD         NUMBER(11,7)    NOT NULL,
    LONGITUD        NUMBER(11,7)    NOT NULL,
    VELOCIDAD       NUMBER(5,1)     DEFAULT 0,
    RUMBO           NUMBER(5,1)     DEFAULT 0,
    PRECISION_M     NUMBER(6,1),
    ESTADO_MOTOR    VARCHAR2(10)    DEFAULT 'ENCENDIDO',
    ODOMETRO        NUMBER(12),
    RECORDED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_GPS_EMPRESA   FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_GPS_VEHICULO  FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_GPS_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES(ID),
    CONSTRAINT CHK_GPS_MOTOR CHECK (ESTADO_MOTOR IN ('ENCENDIDO','APAGADO'))
);

-- ─── GEOCERCAS ──────────────────────────────────────────────
CREATE TABLE GEOCERCAS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    NOMBRE          VARCHAR2(100)   NOT NULL,
    TIPO            VARCHAR2(20)    DEFAULT 'CIRCULO',
    LATITUD_CENTRO  NUMBER(11,7),
    LONGITUD_CENTRO NUMBER(11,7),
    RADIO_M         NUMBER(10),
    ACTIVA          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_GEO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT CHK_GEO_TIPO CHECK (TIPO IN ('CIRCULO','POLIGONO')),
    CONSTRAINT CHK_GEO_ACTIVA CHECK (ACTIVA IN (0,1))
);

-- ─── ALERTAS ────────────────────────────────────────────────
CREATE TABLE ALERTAS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    VEHICULO_ID     VARCHAR2(36),
    CONDUCTOR_ID    VARCHAR2(36),
    TIPO            VARCHAR2(30)    NOT NULL,
    SEVERIDAD       VARCHAR2(10)    NOT NULL,
    MENSAJE         VARCHAR2(500)   NOT NULL,
    RESUELTA        NUMBER(1)       DEFAULT 0 NOT NULL,
    RESUELTA_POR    VARCHAR2(36),
    RESUELTA_AT     TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ALR_EMPRESA   FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_ALR_VEHICULO  FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_ALR_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES(ID),
    CONSTRAINT CHK_ALR_TIPO CHECK (TIPO IN ('VELOCIDAD','GEOCERCA','MANTENCION','STOCK','RALENTI','LICENCIA','COMBUSTIBLE')),
    CONSTRAINT CHK_ALR_SEV CHECK (SEVERIDAD IN ('INFO','WARNING','CRITICAL')),
    CONSTRAINT CHK_ALR_RESUELTA CHECK (RESUELTA IN (0,1))
);

-- ─── ÓRDENES DE TRABAJO ─────────────────────────────────────
CREATE TABLE ORDENES_TRABAJO (
    ID                      VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID              VARCHAR2(36)    NOT NULL,
    NUMERO                  VARCHAR2(20)    NOT NULL,
    VEHICULO_ID             VARCHAR2(36)    NOT NULL,
    TIPO                    VARCHAR2(20)    NOT NULL,
    ESTADO                  VARCHAR2(20)    DEFAULT 'PENDIENTE' NOT NULL,
    DESCRIPCION             VARCHAR2(1000)  NOT NULL,
    MECANICO_RESPONSABLE    VARCHAR2(200),
    AVANCE                  NUMBER(3)       DEFAULT 0,
    COSTO_MANO_OBRA         NUMBER(14,2)    DEFAULT 0,
    COSTO_REPUESTOS         NUMBER(14,2)    DEFAULT 0,
    COSTO_TOTAL             NUMBER(14,2)    DEFAULT 0,
    FECHA_APERTURA          DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_CIERRE_EST        DATE,
    FECHA_CIERRE_REAL       DATE,
    NOTAS                   VARCHAR2(2000),
    ELIMINADO               NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_OT_EMPRESA  FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_OT_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT UQ_OT_NUMERO_EMP UNIQUE (EMPRESA_ID, NUMERO),
    CONSTRAINT CHK_OT_TIPO CHECK (TIPO IN ('PREVENTIVA','CORRECTIVA','NEUMATICOS','ELECTRICA')),
    CONSTRAINT CHK_OT_ESTADO CHECK (ESTADO IN ('PENDIENTE','EN_EJECUCION','BLOQUEADA','CERRADA')),
    CONSTRAINT CHK_OT_AVANCE CHECK (AVANCE BETWEEN 0 AND 100),
    CONSTRAINT CHK_OT_ELIMINADO CHECK (ELIMINADO IN (0,1))
);

-- ─── REPUESTOS ──────────────────────────────────────────────
CREATE TABLE REPUESTOS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    CODIGO          VARCHAR2(50)    NOT NULL,
    DESCRIPCION     VARCHAR2(300)   NOT NULL,
    CATEGORIA       VARCHAR2(100)   NOT NULL,
    UNIDAD          VARCHAR2(20)    DEFAULT 'UN' NOT NULL,
    STOCK_ACTUAL    NUMBER(10)      DEFAULT 0 NOT NULL,
    STOCK_MINIMO    NUMBER(10)      DEFAULT 1 NOT NULL,
    PRECIO_UNITARIO NUMBER(14,2)    DEFAULT 0 NOT NULL,
    PROVEEDOR       VARCHAR2(200),
    ELIMINADO       NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REP_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT UQ_REP_CODIGO_EMP UNIQUE (EMPRESA_ID, CODIGO),
    CONSTRAINT CHK_REP_STOCK CHECK (STOCK_ACTUAL >= 0),
    CONSTRAINT CHK_REP_ELIMINADO CHECK (ELIMINADO IN (0,1))
);

-- ─── DETALLE DE OT (repuestos usados) ───────────────────────
CREATE TABLE DETALLE_OT (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    OT_ID           VARCHAR2(36)    NOT NULL,
    REPUESTO_ID     VARCHAR2(36)    NOT NULL,
    CANTIDAD        NUMBER(10)      NOT NULL,
    PRECIO_UNIT     NUMBER(14,2)    NOT NULL,
    SUBTOTAL        NUMBER(14,2)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DOT_OT       FOREIGN KEY (OT_ID)       REFERENCES ORDENES_TRABAJO(ID),
    CONSTRAINT FK_DOT_REPUESTO FOREIGN KEY (REPUESTO_ID) REFERENCES REPUESTOS(ID)
);

-- ─── MOVIMIENTOS DE STOCK ───────────────────────────────────
CREATE TABLE MOVIMIENTOS_STOCK (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    REPUESTO_ID     VARCHAR2(36)    NOT NULL,
    TIPO            VARCHAR2(20)    NOT NULL,
    CANTIDAD        NUMBER(10)      NOT NULL,
    PRECIO_UNIT     NUMBER(14,2),
    STOCK_ANTERIOR  NUMBER(10)      NOT NULL,
    STOCK_NUEVO     NUMBER(10)      NOT NULL,
    COSTO_TOTAL     NUMBER(14,2),
    REFERENCIA      VARCHAR2(100),
    DOCUMENTO       VARCHAR2(100),
    OT_ID           VARCHAR2(36),
    USUARIO_ID      VARCHAR2(36),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MOV_EMPRESA  FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_MOV_REPUESTO FOREIGN KEY (REPUESTO_ID) REFERENCES REPUESTOS(ID),
    CONSTRAINT FK_MOV_OT       FOREIGN KEY (OT_ID)       REFERENCES ORDENES_TRABAJO(ID),
    CONSTRAINT FK_MOV_USUARIO  FOREIGN KEY (USUARIO_ID)  REFERENCES USUARIOS_SISTEMA(ID),
    CONSTRAINT CHK_MOV_TIPO CHECK (TIPO IN ('ENTRADA','SALIDA','AJUSTE'))
);

-- ─── CARGAS DE COMBUSTIBLE ──────────────────────────────────
CREATE TABLE CARGAS_COMBUSTIBLE (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    VEHICULO_ID     VARCHAR2(36)    NOT NULL,
    CONDUCTOR_ID    VARCHAR2(36),
    NUM_DOCUMENTO   VARCHAR2(50),
    PROVEEDOR       VARCHAR2(100)   NOT NULL,
    ESTACION        VARCHAR2(200),
    FECHA_CARGA     DATE            DEFAULT SYSDATE NOT NULL,
    LITROS          NUMBER(10,2)    NOT NULL,
    PRECIO_LITRO    NUMBER(10,2)    NOT NULL,
    COSTO_TOTAL     NUMBER(14,2)    NOT NULL,
    KM_VEHICULO     NUMBER(12)      NOT NULL,
    CONSUMO_100KM   NUMBER(6,2),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CC_EMPRESA   FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_CC_VEHICULO  FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_CC_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES(ID),
    CONSTRAINT CHK_CC_LITROS CHECK (LITROS > 0)
);

-- ─── SERVICIOS DE TRANSPORTE ────────────────────────────────
CREATE TABLE SERVICIOS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    CLIENTE_ID      VARCHAR2(36)    NOT NULL,
    VEHICULO_ID     VARCHAR2(36),
    CONDUCTOR_ID    VARCHAR2(36),
    NUM_SERVICIO    VARCHAR2(20)    NOT NULL,
    ORIGEN          VARCHAR2(300)   NOT NULL,
    DESTINO         VARCHAR2(300)   NOT NULL,
    KMS_RECORRIDO   NUMBER(10,2),
    FECHA_SERVICIO  DATE            DEFAULT SYSDATE NOT NULL,
    ESTADO          VARCHAR2(20)    DEFAULT 'PENDIENTE' NOT NULL,
    VALOR_NETO      NUMBER(14,2)    NOT NULL,
    IVA             NUMBER(14,2)    NOT NULL,
    VALOR_TOTAL     NUMBER(14,2)    NOT NULL,
    TIPO_DOCUMENTO  VARCHAR2(30)    DEFAULT 'FACTURA',
    NUM_DOCUMENTO   VARCHAR2(50),
    FECHA_FACTURA   DATE,
    FACTURADO       NUMBER(1)       DEFAULT 0 NOT NULL,
    NOTAS           VARCHAR2(1000),
    ELIMINADO       NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SRV_EMPRESA   FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_SRV_CLIENTE   FOREIGN KEY (CLIENTE_ID)  REFERENCES CLIENTES(ID),
    CONSTRAINT FK_SRV_VEHICULO  FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_SRV_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES(ID),
    CONSTRAINT UQ_SRV_NUMERO_EMP UNIQUE (EMPRESA_ID, NUM_SERVICIO),
    CONSTRAINT CHK_SRV_ESTADO CHECK (ESTADO IN ('PENDIENTE','EN_CURSO','COMPLETADO','CANCELADO')),
    CONSTRAINT CHK_SRV_TDOC CHECK (TIPO_DOCUMENTO IN ('FACTURA','BOLETA','GUIA_DESPACHO')),
    CONSTRAINT CHK_SRV_FACTURADO CHECK (FACTURADO IN (0,1)),
    CONSTRAINT CHK_SRV_ELIMINADO CHECK (ELIMINADO IN (0,1))
);
