-- ============================================================
-- Gestión de Flota — Oracle DDL
-- Script 02: Índices y triggers updated_at
-- ============================================================

-- ─── ÍNDICES ────────────────────────────────────────────────
CREATE INDEX IDX_USR_EMPRESA      ON USUARIOS_SISTEMA(EMPRESA_ID);
-- IDX_USR_AZURE_OID omitido: Oracle ya indexa AZURE_OID por su constraint UNIQUE
CREATE INDEX IDX_VEH_EMPRESA      ON VEHICULOS(EMPRESA_ID);
CREATE INDEX IDX_VEH_ESTADO       ON VEHICULOS(EMPRESA_ID, ESTADO);
-- IDX_VEH_QR omitido: Oracle ya indexa QR_CODE por su constraint UNIQUE
CREATE INDEX IDX_COND_EMPRESA     ON CONDUCTORES(EMPRESA_ID);
CREATE INDEX IDX_ASIG_VEHICULO    ON ASIGNACIONES(VEHICULO_ID, ACTIVA);
CREATE INDEX IDX_ASIG_CONDUCTOR   ON ASIGNACIONES(CONDUCTOR_ID, ACTIVA);
CREATE INDEX IDX_GPS_VEHICULO     ON GPS_TRACKS(VEHICULO_ID, RECORDED_AT DESC);
CREATE INDEX IDX_GPS_EMPRESA      ON GPS_TRACKS(EMPRESA_ID, RECORDED_AT DESC);
CREATE INDEX IDX_OT_EMPRESA       ON ORDENES_TRABAJO(EMPRESA_ID, ESTADO);
CREATE INDEX IDX_OT_VEHICULO      ON ORDENES_TRABAJO(VEHICULO_ID);
CREATE INDEX IDX_REP_EMPRESA      ON REPUESTOS(EMPRESA_ID);
CREATE INDEX IDX_MOV_REPUESTO     ON MOVIMIENTOS_STOCK(REPUESTO_ID, CREATED_AT DESC);
CREATE INDEX IDX_CC_VEHICULO      ON CARGAS_COMBUSTIBLE(VEHICULO_ID, FECHA_CARGA DESC);
CREATE INDEX IDX_SRV_CLIENTE      ON SERVICIOS(CLIENTE_ID, FECHA_SERVICIO DESC);
CREATE INDEX IDX_SRV_EMPRESA      ON SERVICIOS(EMPRESA_ID, FACTURADO);
CREATE INDEX IDX_ALR_EMPRESA      ON ALERTAS(EMPRESA_ID, RESUELTA, CREATED_AT DESC);
CREATE INDEX IDX_CLI_EMPRESA      ON CLIENTES(EMPRESA_ID);

-- ─── VISTA: última posición GPS por vehículo ────────────────
CREATE OR REPLACE VIEW GPS_POSICIONES_ACTUALES AS
SELECT *
FROM (
    SELECT
        g.ID, g.EMPRESA_ID, g.VEHICULO_ID, g.CONDUCTOR_ID,
        g.LATITUD, g.LONGITUD, g.VELOCIDAD, g.RUMBO,
        g.ESTADO_MOTOR, g.ODOMETRO, g.RECORDED_AT,
        v.PATENTE, v.MARCA, v.MODELO, v.ESTADO AS ESTADO_VEHICULO,
        c.NOMBRE AS CONDUCTOR_NOMBRE,
        ROW_NUMBER() OVER (PARTITION BY g.VEHICULO_ID ORDER BY g.RECORDED_AT DESC) AS RN
    FROM GPS_TRACKS g
    JOIN VEHICULOS v ON v.ID = g.VEHICULO_ID
    LEFT JOIN CONDUCTORES c ON c.ID = g.CONDUCTOR_ID
)
WHERE RN = 1;

-- ─── VISTA: stock kardex con valorización ───────────────────
CREATE OR REPLACE VIEW KARDEX_REPUESTOS AS
SELECT
    m.ID,
    m.EMPRESA_ID,
    m.REPUESTO_ID,
    r.CODIGO,
    r.DESCRIPCION,
    r.CATEGORIA,
    m.TIPO,
    m.CANTIDAD,
    m.PRECIO_UNIT,
    m.STOCK_ANTERIOR,
    m.STOCK_NUEVO,
    m.COSTO_TOTAL,
    m.REFERENCIA,
    m.DOCUMENTO,
    m.CREATED_AT
FROM MOVIMIENTOS_STOCK m
JOIN REPUESTOS r ON r.ID = m.REPUESTO_ID
ORDER BY m.CREATED_AT DESC;

-- ─── TRIGGERS: UPDATED_AT automático ────────────────────────
CREATE OR REPLACE TRIGGER TRG_EMPRESAS_UPD
    BEFORE UPDATE ON EMPRESAS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIOS_UPD
    BEFORE UPDATE ON USUARIOS_SISTEMA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_VEHICULOS_UPD
    BEFORE UPDATE ON VEHICULOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONDUCTORES_UPD
    BEFORE UPDATE ON CONDUCTORES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_OT_UPD
    BEFORE UPDATE ON ORDENES_TRABAJO
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
    :NEW.COSTO_TOTAL := :NEW.COSTO_MANO_OBRA + :NEW.COSTO_REPUESTOS;
END;
/

CREATE OR REPLACE TRIGGER TRG_REPUESTOS_UPD
    BEFORE UPDATE ON REPUESTOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTES_UPD
    BEFORE UPDATE ON CLIENTES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SERVICIOS_UPD
    BEFORE UPDATE ON SERVICIOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Trigger: actualizar stock al insertar movimiento
CREATE OR REPLACE TRIGGER TRG_MOV_STOCK_INSERT
    AFTER INSERT ON MOVIMIENTOS_STOCK
    FOR EACH ROW
BEGIN
    IF :NEW.TIPO = 'ENTRADA' THEN
        UPDATE REPUESTOS SET STOCK_ACTUAL = STOCK_ACTUAL + :NEW.CANTIDAD WHERE ID = :NEW.REPUESTO_ID;
    ELSIF :NEW.TIPO = 'SALIDA' THEN
        UPDATE REPUESTOS SET STOCK_ACTUAL = GREATEST(0, STOCK_ACTUAL - :NEW.CANTIDAD) WHERE ID = :NEW.REPUESTO_ID;
    ELSIF :NEW.TIPO = 'AJUSTE' THEN
        UPDATE REPUESTOS SET STOCK_ACTUAL = :NEW.CANTIDAD WHERE ID = :NEW.REPUESTO_ID;
    END IF;
END;
/

-- Trigger: calcular consumo_100km al insertar carga combustible
CREATE OR REPLACE TRIGGER TRG_CARGA_COMBUSTIBLE
    BEFORE INSERT ON CARGAS_COMBUSTIBLE
    FOR EACH ROW
DECLARE
    V_KM_ANT NUMBER;
    V_KM_DIFF NUMBER;
BEGIN
    SELECT MAX(KM_VEHICULO) INTO V_KM_ANT
    FROM CARGAS_COMBUSTIBLE
    WHERE VEHICULO_ID = :NEW.VEHICULO_ID AND KM_VEHICULO < :NEW.KM_VEHICULO;

    IF V_KM_ANT IS NOT NULL THEN
        V_KM_DIFF := :NEW.KM_VEHICULO - V_KM_ANT;
        IF V_KM_DIFF > 0 THEN
            :NEW.CONSUMO_100KM := ROUND((:NEW.LITROS / V_KM_DIFF) * 100, 2);
        END IF;
    END IF;
END;
/
