-- ============================================================
-- 04_operaciones.sql  –  Módulo Servicios y Facturación
-- TruckManager Pro – DuocUC
-- ============================================================

-- ── Maestro de tipos de servicio ────────────────────────────
CREATE TABLE TIPOS_SERVICIO (
    ID          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID  VARCHAR2(36)  NOT NULL,
    CODIGO      VARCHAR2(30)  NOT NULL,
    NOMBRE      VARCHAR2(200) NOT NULL,
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT FK_TSRV_EMP   FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT UQ_TSRV_CODIGO UNIQUE (EMPRESA_ID, CODIGO),
    CONSTRAINT CHK_TSRV_ACTIVO CHECK (ACTIVO IN (0,1))
);

-- ── Nuevas columnas en SERVICIOS ────────────────────────────
ALTER TABLE SERVICIOS ADD FECHA_TERMINO    DATE;
ALTER TABLE SERVICIOS ADD IDA_VUELTA       NUMBER(1) DEFAULT 0;
ALTER TABLE SERVICIOS ADD TIPO_SERVICIO_ID VARCHAR2(36);
ALTER TABLE SERVICIOS ADD FACTURA_ID       VARCHAR2(36);

-- ── Tabla de facturas ────────────────────────────────────────
CREATE TABLE FACTURAS (
    ID              VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)  NOT NULL,
    CLIENTE_ID      VARCHAR2(36)  NOT NULL,
    NUM_FACTURA     VARCHAR2(20)  NOT NULL,
    FECHA_EMISION   DATE          DEFAULT SYSDATE NOT NULL,
    SUBTOTAL        NUMBER(14,2)  DEFAULT 0 NOT NULL,
    IVA             NUMBER(14,2)  DEFAULT 0 NOT NULL,
    TOTAL           NUMBER(14,2)  DEFAULT 0 NOT NULL,
    ESTADO          VARCHAR2(20)  DEFAULT 'EMITIDA' NOT NULL,
    NOTAS           VARCHAR2(1000),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_FAC_EMP    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    CONSTRAINT FK_FAC_CLI    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
    CONSTRAINT UQ_FAC_NUM    UNIQUE (EMPRESA_ID, NUM_FACTURA),
    CONSTRAINT CHK_FAC_ESTADO CHECK (ESTADO IN ('EMITIDA','PAGADA','ANULADA'))
);

-- FK de SERVICIOS hacia FACTURAS
ALTER TABLE SERVICIOS ADD CONSTRAINT FK_SRV_FACTURA
    FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID);

-- ── Datos iniciales tipos de servicio para EMP-001 ──────────
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_ACTIVOS',     'Transporte de activos',        1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_VALORES',     'Transporte de valores',        1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_PERSONAS',    'Transporte de personas',       1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_GANADO',      'Transporte de ganado',         1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_LIQUIDOS',    'Transporte de líquidos',       1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_CONTENEDOR',  'Transporte de contenedor',     1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_MAQUINARIA',  'Transporte de maquinaria',     1);
INSERT INTO TIPOS_SERVICIO VALUES (SYS_GUID(),'EMP-001','TRANS_CARGA_GENERAL','Transporte de carga general', 1);
COMMIT;
