-- ============================================================
-- Script 05: Tablas Administración / Almacén
-- ============================================================
CREATE TABLE TAREAS_DEFINICION (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    EMPRESA_ID      VARCHAR2(36)    NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    TIPO_OT         VARCHAR2(20),
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TDEF_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID)
);

CREATE TABLE TAREAS_DEF_ARTICULOS (
    ID              VARCHAR2(36)    DEFAULT SYS_GUID() PRIMARY KEY,
    TAREA_DEF_ID    VARCHAR2(36)    NOT NULL,
    REPUESTO_ID     VARCHAR2(36)    NOT NULL,
    CANTIDAD        NUMBER(10,2)    DEFAULT 1 NOT NULL,
    CONSTRAINT FK_TDA_TAREA    FOREIGN KEY (TAREA_DEF_ID) REFERENCES TAREAS_DEFINICION(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TDA_REPUESTO FOREIGN KEY (REPUESTO_ID)  REFERENCES REPUESTOS(ID)
);
